### ISSUE TITLE
Guid field UpdateFromQuery failed

### ISSUE THREAD

**Issue by trzhou** [NorthernLight1/N.EntityFramework.Extensions#105]
Version: N.EntityFramework.Extensions 1.7.3

1.Defined object:
public class My{
    public Guid? ManByOrgId { set; get; }
    ......
}

2.Update with UpdateFromQuery:
......
Guid? id= Guid.Parse("412b7e4c-323c-461d-899e-eb942b027f9c");
dbcontext.Mys.Where(x => x.kind.Equals("abcd")).UpdateFromQuery(u => new My { ManBySpecId = id });
......

3.SQL statements generated by EntityFramework.Extensions 1.7.3, throw syntax error:
Update ....
SET ManBySpecId=412b7e4c-323c-461d-899e-eb942b027f9c
......

N.EntityFramework.Extensions is great, thanks!

**Comment by jlgarciaATM** [comment]
I got the exact same error.

N.EntityFramework.Extensions is great, thanks!

**Comment by NorthernLight1** [comment]
This issue was resolved in the latest release v1.7.4
