### ISSUE TITLE
BulkUpdate throws 'Sequence contains no matching element' for entities with inheritance

### ISSUE THREAD

**Issue by igormpmartins** [NorthernLight1/N.EntityFramework.Extensions#110]
**Describe the bug**
Whenever I have one class that inherits from another, I'm facing issues which BulkUpdate. When this command runs, the following exception is thrown: "System.InvalidOperationException: Sequence contains no matching element".

The error happens on GetTableMapping, last line, when it create a new instance of TableMapping.

**To Reproduce**
1. Create a class (may be as simple as this):
```
    [Table("Customers")]
    public class Customer
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(255)]
        public string Name { get; set; }
    }
```
2. Create a class that inherits from the previous one
```
    [Table("CustomersPremium")]
    public class CustomerPremium : Customer
    {

    }
```
3. Add both classes to your database context.
4. Populate data to your tables. In my case, I have just 6 records.
5. Perform changes on the entity and use BulkUpdate, exception should be thrown:
```
                var customers = context.Customers.ToList();

                foreach (var c in customers)
                    c.Name += '.';

                
                context.BulkUpdate(customers);
                context.SaveChanges();
```

Please, is there any workaround for this? Or doesn't this library support entity inheritance?

**Comment by NorthernLight1** [comment]
Hi igormpmartins,

Please provide the backend schema for these table so I can easily see what inheritance is being used. In the example above, put some properties in CustomerPremium and then provide the SQL schema in the database.

**Comment by igormpmartins** [comment]
Hi @NorthernLight1 

Thanks so much for replying. Sure, I added some attributes to the class CustomerPremium and here's the updated version:
```
    [Table("CustomersPremium")]
    public class CustomerPremium : Customer
    {
        [MaxLength(255)]
        public string SubscriptionPlan { get; set; }
        public bool VIP { get; set; }
    }

```

Here is the SQL schema for both tables:
```
CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NULL,
 CONSTRAINT [PK_dbo.Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CustomersPremium](
	[Id] [int] NOT NULL,
	[SubscriptionPlan] [nvarchar](255) NULL,
	[VIP] [bit] NOT NULL,
 CONSTRAINT [PK_dbo.CustomersPremium] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CustomersPremium] ADD  DEFAULT ((0)) FOR [VIP]
GO

ALTER TABLE [dbo].[CustomersPremium]  WITH CHECK ADD  CONSTRAINT [FK_dbo.CustomersPremium_dbo.Customers_Id] FOREIGN KEY([Id])
REFERENCES [dbo].[Customers] ([Id])
GO

ALTER TABLE [dbo].[CustomersPremium] CHECK CONSTRAINT [FK_dbo.CustomersPremium_dbo.Customers_Id]
GO
```

**Comment by igormpmartins** [comment]
I had this issue while testing the library on another project. For this reason, I created a much more simplified project for isolating the issue. If needed, I can provide the complete source code, since it uses DB First approach.

**Comment by NorthernLight1** [comment]
Hi Igormpmartins,

It appears that you are using Table-Per-Type Inheritance, which is not supported by the framework at this time. It only supports Table-Per-Concrete and Table-Per-Hierarchy. I will do some research on how easy this could be added but I can't make any promises on it.
