### ISSUE TITLE
There is an exception with DeleteFromQueryAsync and queries with Joins

### ISSUE THREAD

**Issue by PabloFerroDev** [NorthernLight1/N.EntityFramework.Extensions#121]
**Describe the bug**
I want to delete a parent table records using a query that connects with a join with another table (the child collection). I'm having an exception "Incorrect syntax near the keyword 'ON'

Looks like the SQL query is not being generated correctly. It is trying to execute:

DELETE [Extent2] ON [Extent1].[ProductId] = [Extent2].[Id]
FROM [dbo].[Orders] AS [Extent1]     INNER JOIN [dbo].[Products] AS [Extent2] ON [Extent1].[ProductId] = [Extent2].[Id]
WHERE [Extent2].[OutOfStock] = 1

but it should be generating this

DELETE [dbo].[Orders]
FROM [dbo].[Orders] AS [Extent1]     INNER JOIN [dbo].[Products] AS [Extent2] ON [Extent1].[ProductId] = [Extent2].[Id]
WHERE [Extent2].[OutOfStock] = 1

**To Reproduce**
1. Create records that can hold a link between them. For example, Orders should have Products connected through a foreign key
2. Call DeleteFromQueryAsync like this: `await dbContext.Orders.Where(x => **x.Product.OutOfStock).DeleteFromQueryAsync();**`
3. Exception should occurr.

**Expected behavior**
DeleteFromQueryAsync should generate a valid SQL Query statement and it should throw no error.

**Comment by PabloFerroDev** [comment]
I have already fixed this but I'm not sure you are going to like my fix.

I have changed GetTableAlias to this:

`public String GetTableAlias(bool isDelete)
{
    var sqlFromClause = Clauses.First(o => o.Name == "FROM");
    var startIndex = 0;
    if (isDelete && sqlFromClause.InputText.Contains("JOIN"))
    {
        startIndex = sqlFromClause.InputText.IndexOf(" AS ");

        return startIndex > 0 ? sqlFromClause.InputText.Substring(0, startIndex) : "";
    }
    else
    {
        startIndex = sqlFromClause.InputText.LastIndexOf(" AS ");

        return startIndex > 0 ? sqlFromClause.InputText.Substring(startIndex + 4) : "";
    }
}`

I'm not sure this is the path you want to take. Let me know!

**Comment by NorthernLight1** [comment]
This issue was addressed in [1.8.1](https://www.nuget.org/packages/N.EntityFramework.Extensions/1.8.1)
