### ISSUE TITLE
Foreign Keys on child objects are failing the SQL Merge in BulkInsertAsync

### ISSUE THREAD

**Issue by Chimera93** [NorthernLight1/N.EntityFramework.Extensions#123]
**Describe the bug**
We have two models, each in their own table, and a parent/child type of relationship between the two. There are ForeignKey data annotations on the child model to reference the identity column on the parent model. The data is loaded using .Include() when returning the parent model, and standard EF6 works correctly calling SaveChangesAsync().

**To Reproduce**
1. Create a unit test with two models as below
[Table("ModelA")]
public partial class ModelA
{
    [Key]
    public int ID { get; set; }
    public double? Points { get; set; }
    public virtual ICollection<ModelB> ModelBs { get; set; }
}

[Table("ModelB")]
public class ModelB
{
    [Key]
    public int ID { get; set; }

    [ForeignKey("ModelA")]
    public int ModelA_ID { get; set; }
    public string Notes { get; set; }
    public virtual ModelA ModelA { get; set; }
}
2. Add a sampling of model A objects with some model B objects in the instantation. Don't populate the IDS or foreign key values because those should be handled.
3. The insert is correctly applying the identity column back to the parent model on insert, but the child object is merged with an foreign key value of 0, which causes the below sql error.

**Expected behavior**
I would expect the identity value coming back from the BulkQuery after the merge to apply the Id to child objects as well.

**Screenshots**
The MERGE statement conflicted with the FOREIGN KEY constraint "FK_dbo.ModelB_dbo.ModelA_ModelA_ID". The conflict occurred in database "N.EntityFramework.Extensions.Test.Data.TestDbContext", table "dbo.ModelA", column 'ID'.

**Comment by Chimera93** [comment]
This is also a problem regardless of if the foreignkey attribute is on the parent element or the child element or both

**Comment by NorthernLight1** [comment]
Chimera93, 

This framework does not have support to automatically save child entities at this time.

You could try to call BulkInsert() on the child entities first and then the parent ones after, and that should
