### ISSUE TITLE
Proxy entities type not detected correctly, generic method using object as type fails

### ISSUE THREAD

**Issue by Naekhrah** [NorthernLight1/N.EntityFramework.Extensions#125]
**Describe the bug**

BulkSaveChanges with proxy entity type (ie Blog_5E43C6C196972BF0754973E48C9C941092D86818CD94005E9A759B70BF6E48E6) fails when it tries to determine the TableMapping with the System.Object type because there is no proxy type loaded in the metadata.

**To Reproduce**

Create entity with proxy creation, add to context, do bulk save.

**Expected behavior**

Using proxy should save the entities the same as without proxy entities.

**Additional context**

This line here should be fixed to ignore proxy suffix: 

foreach (var saveEntryGroup in entries.GroupBy(o => new { EntityType=o.Entity.GetType(), o.State }))

o.Entity.GetType() returns the type with the suffix ie Blog_5E43C6C196972BF0754973E48C9C941092D86818CD94005E9A759B70BF6E48E6

Using ObjectContext.GetObjectType() should get the actual object type of Blog

https://learn.microsoft.com/en-us/ef/ef6/fundamentals/proxies

**Comment by NorthernLight1** [comment]
Naekhrah,

Thanks for reporting this issue and providing the additional information from Microsoft. It helped me fix the issue quickly.  

This issue was resolved in v1.8.2.

I added new tests to cover this issue for BulkSaveChanges() and BulkInsert().

**Comment by Naekhrah** [comment]
Seems to be working now @NorthernLight1 👌
