### ISSUE TITLE
Null exception

### ISSUE THREAD

**Issue by edfloreshz** [NorthernLight1/N.EntityFramework.Extensions#128]
**Describe the bug**
I'm trying to call a `BulkMerge` but I'm facing this: `Object reference not set to an instance of an object.`

Stack Trace:
```
N.EntityFramework.Extensions.DbTransactionContext.DbTransactionContext(System.Data.Entity.DbContext context, N.EntityFramework.Extensions.Enums.ConnectionBehavior connectionBehavior, System.Data.Entity.TransactionalBehavior transactionalBehavior, int? commandTimeout, bool openConnection)
 	N.EntityFramework.Extensions.DbTransactionContext.DbTransactionContext(System.Data.Entity.DbContext context, N.EntityFramework.Extensions.BulkOptions options)
 	N.EntityFramework.Extensions.DbContextExtensions.InternalBulkMerge<Model>(System.Data.Entity.DbContext context, System.Collections.Generic.IEnumerable<Model> entities, N.EntityFramework.Extensions.BulkMergeOptions<Model> options)
 	N.EntityFramework.Extensions.DbContextExtensions.BulkMerge<Model>(System.Data.Entity.DbContext context, System.Collections.Generic.IEnumerable<Model> entities, N.EntityFramework.Extensions.BulkMergeOptions<Model> options)
 	N.EntityFramework.Extensions.DbContextExtensions.BulkMerge<Model>(System.Data.Entity.DbContext context, System.Collections.Generic.IEnumerable<Model> entities)

```

**To Reproduce**
1. Call `BulkUpdate` method.

**Expected behavior**
Correct handling of null values.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 125.0.2535.67

**Comment by NorthernLight1** [comment]
edfloreshz,

I am going to need more information to troubleshoot this issue. There are test cases that cover this function and they passed on the last release so there maybe something unique to your project.

1. Does this issue happen with different entity types?
2. Are you using EF 6.4.4?
3. What version of .NET are you using?
4. Are you targeting SQL Server or another database provider?

**Comment by edfloreshz** [comment]
1. I tried 3 different types and I faced the issue with all of them.
2. Yes, I installed that version to see if the issue persisted.
3. .NET 4.8
4. I'm targeting an Oracle database.

**Comment by NorthernLight1** [comment]
edfloreshz,

Sorry about that but this library only supports SQL Server. I will make sure to update the documentation to avoid any further confusion.

**Comment by edfloreshz** [comment]
Ah that makes sense! No worries, do you think Oracle could be supported at some point?

**Comment by NorthernLight1** [comment]
I am not very familiar with Oracle but if someone wanted to add support for it, they could. 

I would suggest you check out this library: https://www.nuget.org/packages/Z.BulkOperations

**Comment by edfloreshz** [comment]
Thanks 🙏🏼
