### ISSUE TITLE
Bug with tables with triggers in database

### ISSUE THREAD

**Issue by Naekhrah** [NorthernLight1/N.EntityFramework.Extensions#130]
**Describe the bug**
Triggers in database seem to cause this error with BulkSaveChanges

`The target table 't' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.`

**To Reproduce**
1. Have a entity mapped to a table with trigger(s)
2. Add entities to that dbset
3. Call BulkSaveChanges

**Expected behavior**
The added entities are added to the entity table and the db rows added by the trigger are also included in the db.

**Comment by NorthernLight1** [comment]
This issue was fixed in v1.8.4. In order to use it though, you will have to disable the autoMapOut feature so any auto-generated fields from the database will not be automatically populated like an Id field.

`int rowsAffected = dbContext.BulkSaveChanges(autoMapOutput:false);`
