### ISSUE TITLE
UpdateFromQueryAsync fails with empty contains.

### ISSUE THREAD

**Issue by PabloFerroDev** [NorthernLight1/N.EntityFramework.Extensions#136]
When you use UpdateFromQueryAsync, from a query that has an empty .Contains(), something similar to this solved bug happens: #122

**Comment by PabloFerroDev** [comment]
Added a pull request here:

[https://github.com/NorthernLight1/N.EntityFramework.Extensions/pull/137](url)

**Comment by PabloFerroDev** [comment]
Added a pull request (updated)

#139

**Comment by NorthernLight1** [comment]
The PR for this bug has been approved and released in v1.9.0.
