### ISSUE TITLE
Unwanted transaction rollback when library does not own transaction

### ISSUE THREAD

**Issue by PabloFerroDev** [NorthernLight1/N.EntityFramework.Extensions#140]
**Describe the bug**
If something happens with the sql command (for example, a int overflow), the transaction is always rolled back even if the library does not own the library. Transaction rollback should be handled by the code who created it, the same way that DbTransactionContext.Commit works.

**To Reproduce**
1. Set something that can cause an Update or Insert to fail in the database, such as a int limit, nvarchar limit, unique key.
2. Create a transaction outside the library code that opens a transaction
3. Catch the error when the sql command fails, and try to rollback the exception. Because the exception has already been rollbacked, the user code also fails.

**Expected behavior**
If the library does not own the connection, then it should not rollback it.

**Additional context**
I attach here a pull request with the fix + a test. #141

**Comment by NorthernLight1** [comment]
The PR for this bug has been approved and released in v1.9.0.
