### ISSUE TITLE
BulkInsert always uses permanent table, why ?

### ISSUE THREAD

**Issue by LukeOrdelmans** [NorthernLight1/N.EntityFramework.Extensions#53]
Awesome library, thank you!

Is there a reason why BulkInsert no longer uses the UsePermanentTable option? (or did I find a bug)

`string stagingTableName = GetStagingTableName(tableMapping, true, dbConnection);`

the **true** in this line used to be **options.UsePermanentTable** 

I have no CREATE TABLE access on every database we target, so I would prefer the option, for now I downgraded to 1.5.0

**Comment by NorthernLight1** [comment]
Thanks, I did this as a side project to use for work and it has come in quite handy.

Yes what you have mention above is a bug that was introduced with the previous fix. I have gone ahead and fixed it in the latest Nuget version.

If you find any other issues, let me know.

**Comment by LukeOrdelmans** [comment]
Awesome, thanks  :thumbsup:
