### ISSUE TITLE
Fetch() failed with DateTime parameter

### ISSUE THREAD

**Issue by EricY-2021** [NorthernLight1/N.EntityFramework.Extensions#56]
I updated to the latest 1.5.2 from nuget.

Query 
```
var yesterday = DateTime.Now.AddDays(-1);
var dbcontext = new MyDbContext();  
var query = dbcontext.Member.Where(o => o.member_create_date > yesterday);
query.Fetch(result =>
  {
    batchCount++;
    totalCount += result.Results.Count();
  }, 
  new FetchOptions { BatchSize = 1000 }
);

return query.toList();
```

And I got this exception:  Must declare the scalar variable \"@p__linq__0\".
database is Sql Server
column type is datetime

**Comment by NorthernLight1** [comment]
EricY-2021

This issue has been fixed in 1.5.3. Please re-test and let me know if you find any further issues.

**Comment by EricY-2021** [comment]
Yes, I tested it, and it works like a charm now. Thank you!

**Comment by EricY-2021** [comment]
I found another issue when calling BulkInsert.

Exception message: Sequence contains no matching element.
Stack trace: "   at N.EntityFramework.Extensions.DbContextExtensions.GetTableMapping(IObjectContextAdapter context, Type type)\r\n   at N.EntityFramework.Extensions.DbContextExtensions.BulkInsert[T](DbContext context, IEnumerable`1 entities, BulkInsertOptions`1 options)\r\n   at N.EntityFramework.Extensions.DbContextExtensions.BulkInsert[T](DbContext context, IEnumerable`1 entities)\r\n   at CircleK.Common.EntityFramework.RepositoryBase`1.BulkInsert(List`1 entities)

My code:
```
            var messages = mappingListMemberIds.Select(m => new Message()
            {
                Body = messageDto.Body ?? "",
                Body_En = messageDto.BodyEn ?? "",
                CreatedTime = DateTime.Now,
                EventID = messageDto.EventId,
                Title = messageDto.Title ?? "",
                Title_En = messageDto.TitleEn ?? "",
                MsgQueueID = 0,
                UID = m
            }).ToList();

      _dataContext.BulkInsert(messages);
```
But I tried OK with nomal entity framework Insert.

**Comment by NorthernLight1** [comment]
Do you have a DbSet<Message> property defined within your DbContext? Can you provide a copy of your Message class so I can try to replicate it?

**Comment by EricY-2021** [comment]
Hi NorthernLight,

```
    [Table("Message")]
    public partial class Message
    {
        public int ID { get; set; }

        public DateTime CreatedTime { get; set; }

        [Required]
        [StringLength(128)]
        public string Title_En { get; set; }

        [Required]
        [StringLength(128)]
        public string Title { get; set; }

        [Required]
        [StringLength(512)]
        public string Body_En { get; set; }

        [Required]
        [StringLength(512)]
        public string Body { get; set; }

        [StringLength(128)]
        public string ImageUrl { get; set; }

        public DateTime? ValidStart { get; set; }

        public DateTime? ValidEnd { get; set; }

        public int UID { get; set; }

        public bool Readed { get; set; }

        public DateTime? OpenedTime { get; set; }

        public int MsgQueueID { get; set; }

        public int? RecordType { get; set; }

        public int? RecordID { get; set; }

        public int? PromID { get; set; }

        public int? EventID { get; set; }

        [StringLength(128)]
        public string Url { get; set; }
    }
```

**Comment by NorthernLight1** [comment]
EricY-2021,

I have fixed the issue you mentioned above, it was because you were using a Database First model. Please download the latest Nuget version 1.5.4 and let me know if it works for you.

**Comment by EricY-2021** [comment]
Awesome library! The issue has been fixed. Thank you！
