### ISSUE TITLE
Allow for transaction control

### ISSUE THREAD

**Issue by monkeyhouse** [NorthernLight1/N.EntityFramework.Extensions#64]
**Is your feature request related to a problem? Please describe.**
I need the ability to rollback a transaction. Sometimes an unrelated operation fails, and when it does, I want to be able to roll back the bulk insert, update, etc.

**Describe the solution you'd like**
Ideally, I'd like it to use an existing transaction if there is one open on the entity framework Context. This would means the controlling transaction would be responsible for the ultimate commit or rollback.

**Comment by NorthernLight1** [comment]
monkeyhouse,

The framework has been updated so that all methods now supports external transactions. If you find any issue related to it, let me know.

**Example: Using A Transaction With BulkInsert** 
using (var transaction = dbContext.Database.BeginTransaction())
{
           int rowsInserted = dbContext.BulkInsert(orders);
           transaction.Commit();
}
