### ISSUE TITLE
BulkUpdate,IgnoreColumnsOnUpdate  doesn't work

### ISSUE THREAD

**Issue by LeanCai** [NorthernLight1/N.EntityFramework.Extensions#70]
when i want to BulkUpdate the table but need ignore some columns. it doesn't work.
```
 static void Main(string[] args)
        {
            using (OceanStarerpEntities db = new OceanStarerpEntities())
            {
                var list = db.p_SubBarCode.Where(x => x.Id <= 100).ToList();

                int i = 0;
                foreach (var item in list)
                {
                    item.Remark = $"remark {i++}";
                }
                Console.WriteLine(list.Count);

                db.BulkUpdate(list, options =>
                {
                    options.IgnoreColumnsOnUpdate = x => x.Timestamp;
                });

                Console.WriteLine(list.Count);
                Console.ReadKey();
            }
        }
```
```
UPDATE t SET t.[ProductFamily]=s.[ProductFamily],t.[SubBarCode]=s.[SubBarCode],t.[BarCodeType]=s.[BarCodeType]
  ,t.[OriginalBarCode]=s.[OriginalBarCode],t.[ProductEnName]=s.[ProductEnName],t.[Remark]=s.[Remark]
  ,t.[Sy_Delete]=s.[Sy_Delete],t.[Sy_Guid]=s.[Sy_Guid],t.[Sy_Time]=s.[Sy_Time],t.[Timestamp]=s.[Timestamp]
FROM [dbo].[#tmp_be_xx_p_SubBarCode] AS s 
JOIN [dbo].[p_SubBarCode] AS t ON s.Id=t.Id; 
SELECT @@RowCount;
```

![image](https://user-images.githubusercontent.com/38241378/167092255-90a41d6d-b971-4232-90c3-65855dccdf85.png)

I ignore the column, But the column still exists

**Comment by LeanCai** [comment]
i also hope that, when the column type is **timestamp**, bulkupdate can ignore the column

![image](https://user-images.githubusercontent.com/38241378/167095233-fc3d5512-60b9-48a0-bb26-1c280f32d370.png)

**Comment by NorthernLight1** [comment]
LeanCai,

I fixed the issue you described and it should work now. I also added a new test to cover this. Please test and let me know if it is still an issue.

**Comment by LeanCai** [comment]
It works as I use it like this：
```
                db.BulkUpdate(list, options =>
                {
                    options.IgnoreColumnsOnUpdate = x => new { x.Timestamp };
                });
```
,But it doesn't works when i use like that:
```
                db.BulkUpdate(list, options =>
                {
                    options.IgnoreColumnsOnUpdate = x => x.Timestamp;
                });
```

**Comment by LeanCai** [comment]
ok，it works anyway.

**Comment by NorthernLight1** [comment]
Thanks, I will address this issue soon.

**Comment by LeanCai** [comment]
I also need this function. I need to ignore some fields when inserting data

**Comment by NorthernLight1** [comment]
LeanCai,

I have added the functionality you requested so that the BulkInsert() now includes Options.IgnoreColumns. I decided not to call it IgnoreColumnsOnInsert since BulkInsert only does inserts, it is redundant. 

In a future enhancement, I plan depredate BulkUpdate.IgnoreColumnsOnUpdate and rename it to IgnoreColumns, but you don't have to worry since both will be supported.

I also fixed options.IgnoreColumnsOnUpdate in both BulkInsert() and BulkUpdate() so that it accepts either a string or anonymous type. That means both examples you mentioned above will work.

Please test it out and let me know if you encounter any issue with it. If you find any new bugs unrelated to this discussion or want to request new functionality, please open a new issue.

**Comment by LeanCai** [comment]
My suggested code
```
        static List<string> GetObjectProperties<T>(Expression<Func<T, object>> expression)
        {
            if (expression == null)
            {
                return new List<string>();
            }
            else
            {
                var propertyExpression = expression.Body as MemberExpression;
                if (propertyExpression != null)
                {
                    return new List<string> { propertyExpression.Member.Name };
                }
                var newExpression = expression.Body as NewExpression;
                if(newExpression != null)
                {
                    var result = newExpression.Members.Select(x => x.Name).ToList();
                    return result;
                }
                return new List<string>();
            }
        }
```

**Comment by NorthernLight1** [comment]
LeanCai,

I re-wrote the code with your suggestion above but tweaked it a little bit. Thanks for the help!

I also added BulkUpate.IgnoreColumns and marked BulkUpdate.IgnoreColumnsOnUpdate as obsolete. 

BulkInsert has IncludeColumns as well so you can control the input columns, but for your case IgnoreColumns sounds like the best option.

If you notice any other bugs, please let me know, I will add test cases for them.
