### ISSUE TITLE
Exception thrown calling BulkInsert if AutoMapOutputIdentity is true and the class has more than one key property

### ISSUE THREAD

**Issue by thecodefish** [NorthernLight1/N.EntityFramework.Extensions#85]
**Describe the bug**
When using BulkInsert, if the class you are inserting has a complex primary key (multiple key properties), the insert fails with an `ArgumentOutOfRangeException`.

I've managed to find the code in question and I think this should be an easy fix, it looks like a logic error.

In DbContextExtensions.cs line 143:
![image](https://user-images.githubusercontent.com/2665874/189467190-ec176768-a2aa-418b-abfc-fb688a03d239.png)

I believe `propertySetters[2-i]` should be `propertySetters[i-2]`.

When i = 2, the index is 0, but when i = 3, the index is -1 (and should be 1).

I'm aware that in this case I shouldn't be using AutoMapOutputIdentity (because there are no identity columns that need mapping), but the error was still unexpected.

**To Reproduce**
Example class that triggers the problem:

````c#
public class ItemWithComplexKey {
  [Key, Column(Order = 1)]
  public int Key1 { get; set; }
  [Key, Column(Order = 2)]
  public int Key2 { get; set; }
  public decimal Value { get; set; }
}
````

**Comment by NorthernLight1** [comment]
thecodefish,

Thanks for reporting this issue. It has been fixed in the latest version (v1.6.6) and a test case has been added to cover both BulkInsert() and BulkInsertAsync(). Please re-test it and let me know if it is still an issue.
