### ISSUE TITLE
Add AutoMapOutputIdentity Support To BulkInsert

### ISSUE THREAD

**Issue by NorthernLight1** [NorthernLight1/N.EntityFramework.Extensions#9]
When calling the BulkInsert(), the entities should have their id's set to the auto-generated id(s) set by the database. This feature can be disabled/enabled by the options.AutoMapOutputIdentity flag.

**Comment by nqbjnh** [comment]
How to use AutoMapOutputIdentity?
I get DLL from nuget, but AutoMapOutputIdentity not working with id column.
I try got your project and build failed
Error: "The type or namespace name 'BulkInsertResult<>' could not be found"

**Comment by nqbjnh** [comment]
I get your project and create table Order on my Sql Server. => AutoMapOutputIdentity not working, how use it.
This is my code:

![auto-map-identity-failed](https://user-images.githubusercontent.com/26054523/102036360-362af980-3df5-11eb-8837-3201c768f6cb.png)

**Comment by nqbjnh** [comment]
I edited BulkInsert function and it work, you can help me check it.

	public static int BulkInsert<T>(this DbContext context, IEnumerable<T> entities, BulkInsertOptions<T> options)
	{
		var rowsAffected = 0;
		var tableMapping = context.GetTableMapping(typeof(T));
		var dbConnection = context.GetSqlConnection();
		int rowsInserted = 0;

		if (dbConnection.State == ConnectionState.Closed)
			dbConnection.Open();

		using (var transaction = dbConnection.BeginTransaction())
		{
			try
			{
				string stagingTableName = GetStagingTableName(tableMapping, options.UsePermanentTable, dbConnection);
				string destinationTableName = string.Format("[{0}].[{1}]", tableMapping.Schema, tableMapping.TableName);
				string[] columnNames = tableMapping.Columns.Where(o => !o.Column.IsStoreGeneratedIdentity).Select(o => o.Column.Name).ToArray();
				string[] storeGeneratedColumnNames = tableMapping.Columns.Where(o => o.Column.IsStoreGeneratedIdentity).Select(o => o.Column.Name).ToArray();

				SqlUtil.CloneTable(destinationTableName, stagingTableName, null, dbConnection, transaction, Common.Constants.Guid_ColumnName);
				var bulkInsertResult = BulkInsert(entities, options, tableMapping, dbConnection, transaction, stagingTableName, null, SqlBulkCopyOptions.KeepIdentity, true);

				IEnumerable<string> columnsToInsert = columnNames;

				List<string> columnsToOutput = new List<string> ();
				List<PropertyInfo> propertySetters = new List<PropertyInfo>();
				Type entityType = typeof(T);

				foreach (var storeGeneratedColumnName in storeGeneratedColumnNames)
				{
					columnsToOutput.Add(string.Format("inserted.[{0}]", storeGeneratedColumnName));
					propertySetters.Add(entityType.GetProperty(storeGeneratedColumnName));
				}

				string mergeSqlText = string.Format("INSERT INTO {0} OUTPUT {1} SELECT {2} FROM {3};",
					destinationTableName, SqlUtil.ConvertToColumnString(columnsToOutput), SqlUtil.ConvertToColumnString(columnsToInsert), stagingTableName
					);

				var bulkQueryResult = context.BulkQuery(mergeSqlText, dbConnection, transaction);
				rowsAffected = bulkQueryResult.RowsAffected;

				if (options.AutoMapOutputIdentity)
				{
					if (rowsAffected == entities.Count())
					{
						var entityIndex = 1;
						bulkQueryResult.Results.ToList().ForEach(x =>
						{
							var id = long.Parse(x.FirstOrDefault().ToString());
							var entity = bulkInsertResult.EntityMap[entityIndex];
							propertySetters[0].SetValue(entity, id);
							entityIndex++;
						});
					}
				}
				
				SqlUtil.DeleteTable(stagingTableName, dbConnection, transaction);

				//ClearEntityStateToUnchanged(context, entities);
				transaction.Commit();
				return rowsAffected;
			}
			catch (Exception ex)
			{
				transaction.Rollback();
				throw ex;
			}
			finally
			{
				dbConnection.Close();
			}

		}
	}

**Comment by NorthernLight1** [comment]
nqbjnh,

I have reviewed and added your code to the master branch. I made a few tweaks but it mostly what you submitted. I also enabled the test case for BulkInsert_Options_AutoMapIdentity.

If you write any new code, please create a fork of the master branch and then create a pull requests going forward if that possible. It would make it easier to merge and you would get direct credit within Github.
