### ISSUE TITLE
Only works with MARS connections

### ISSUE THREAD

**Issue by flemingtech** [NorthernLight1/N.EntityFramework.Extensions#96]
**Describe the bug**
I was trying to use this library to replace a deprecated one, and was having all sorts of issues with this. So I ran the built in tests and most of them passed (couple minor exceptions). So to make it more close to my environment I went to change the connection string to my server... And that's when I noticed this "MultipleActiveResultSets=True"

When I set this to 'False' then most, if not all, the tests failed in the same way my application was. Any chance we can remove this restriction from the library?

Message: 
Test method N.EntityFramework.Extensions.Test.DbContextExtensions.BulkInsert.With_Complex_Key threw exception: 
System.Data.Entity.Core.EntityException: The underlying provider failed on Rollback. ---> System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.

  Stack Trace: 
SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
SqlInternalTransaction.Rollback()
SqlTransaction.Rollback()
InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
DbTransactionDispatcher.Rollback(DbTransaction transaction, DbInterceptionContext interceptionContext)
EntityTransaction.Rollback()
--- End of inner exception stack trace ---
EntityTransaction.Rollback()
DbTransactionContext.Rollback() line 66
DbContextExtensions.BulkInsert[T](DbContext context, IEnumerable`1 entities, BulkInsertOptions`1 options) line 210
DbContextExtensionsBase.SetupDbContext(Boolean populateData, PopulateDataMode mode) line 76
BulkInsert.With_Complex_Key() line 16

**Comment by flemingtech** [comment]
I'm replying to myself here. Seems like MARS was a symptom.

I got all of the built in tests to pass without MARS set, by making the following change. It would appear that DbContextExtensions.BulkQuery() was opening a reader and not closing it.

Wrapping it in a using seems to have fixed my issues.

![image](https://user-images.githubusercontent.com/7074286/207146938-6ce70811-552a-4f26-8259-28aed457b362.png)

**Comment by NorthernLight1** [comment]
flamingtech,

Thanks for the finding this issue. It will be addressed in the next release.

**Comment by flemingtech** [comment]
No, thank you for such a building and maintaining such a useful tool.

Brett Fleming
***@***.***
www.flemingtechinc.com

**Comment by NorthernLight1** [comment]
This item was fixed in the latest release v1.7.4.
