### ISSUE TITLE
Cannot install on .NET 4.8

### ISSUE THREAD

**Issue by clabough** [NorthernLight1/N.EntityFramework.Extensions#98]
Trying to install on .NET 4.8 gives the following error

`Package N.EntityFrameworkCore.Extensions 6.0.8.3 is not compatible with net48 (.NETFramework,Version=v4.8). Package N.EntityFrameworkCore.Extensions 6.0.8.3 supports: net6.0 (.NETCoreApp,Version=v6.0)`

**Comment by iamSathishMohan** [comment]
@clabough - you are using .net core version of the library in .netframework project. Please look for the right one while installing it or using the following comment in the package manager console window to install it.

`Install-Package N.EntityFramework.Extensions`

**Comment by clabough** [comment]
Thanks. I didn't catch that small difference.
